apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: matmulsched-deployment
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: matmulsched-deployment
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - image: registry.digitalocean.com/<my-registry>/<my-image>
            name: matmulsched-deployment
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/5 * * * *'
status: {}
