apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      labels:
        app: api-deployment
    spec:
      containers:
      - name: api-deployment
        image: ${{digital_ocean_registry}}
        resources:
          limits:
            memory: "500Mi" # 128 megabytes
            cpu: "50m" # not more than 
        ports:
        - containerPort: 9696
