apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api-deployment
spec:
  type: LoadBalancer
  selector:
    app: api-deployment
  ports:
    - protocol: TCP
      name: http
      port: 9696
      targetPort: 9696
