apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataloader-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataloader-deployment
  template:
    metadata:
      labels:
        app: dataloader-deployment
    spec:
      containers:
      - name: dataloader-deployment
        image: registry.digitalocean.com/<my-registry>/<my-image>
        env:
        - name: ENDPOINT_URL
          value: ${ENDPOINT_URL}
        - name: SECRET_KEY
          value: ${SECRET_KEY}
        - name: SPACES_ID
          value: ${SPACES_ID}
        - name: SPACES_NAME
          value: ${SPACES_NAME}
        resources:
          limits:
            memory: "500Mi" # 128 megabytes
            cpu: "50m" # not more than 
        ports:
        - containerPort: 9696

